### ISSUE TITLE
GET /frontend/bower_components/webcomponentsjs/webcomponents-lite.min.js 404

### ISSUE THREAD

**Issue by sunjunlishi** [actions-on-google/actionssdk-smart-home-nodejs#10]
could not find the file webcomponents-lite.min.js ,where is it

**Comment by entertailion** [comment]
Did you do a "bower install" to install all the dependencies?

**Comment by sunjunlishi** [comment]
GET /frontend/bower_components/iron-selector/iron-selection.html 200 0.723 ms - 3452
GET /frontend/bower_components/web-animations-js/web-animations-next-lite.min.js 200 0.585 ms - 49964
POST /smart-home-api/status 403 1.243 ms - 24
POST /smart-home-api/auth 200 1.391 ms - 16

thanks i have resolved it
