### ISSUE TITLE
Knowing the assistant language

### ISSUE THREAD

**Issue by guzmanvig** [actions-on-google/actionssdk-smart-home-nodejs#107]
Is there a way to know what was the language the user was speaking when talking to the assistant so I can provide fulfillment in different languages?

Thanks

**Comment by Fleker** [comment]
What kind of fulfillment are you trying to do? Using the Smart Home APIs, you don't need to worry about the user's locale as the Assistant processes the text and sends a structured request to your payload.

**Comment by guzmanvig** [comment]
Yes, I'm using the smart home API. I understand what you are saying, however I do need to know the user's locale because in some cases the name of the device I want to return to google dependes on the language. For example, if I know light is in the kitchen, I name it "kitchen light", however, if the user is speaking in german I should name it "(same but in german)"

**Comment by Fleker** [comment]
As part of Smart Home, this information is not really necessary.

The user places the device in their home and can configure its location from the Assistant settings, and that is not something which is sent back to the cloud provider.

As the Assistant knows it is a light, and it's in the kitchen, a query relating to a kitchen light will work as this vocabulary has already been built out across locales. You don't need to provide it. Additionally, international users are able to give custom nicknames, overriding it.

Getting the locale of the user is not something supported by the API. However, if you do want to use it, you can make it part of the account linking process, where you obtain and store this information and then use it in your SYNC.

**Comment by guzmanvig** [comment]
Okay, that was clear

Thank you very much
