### ISSUE TITLE
Account linking failed

### ISSUE THREAD

**Issue by antoniosap** [actions-on-google/actionssdk-smart-home-nodejs#110]
this is the response to:

```
https://oauth-redirect.googleusercontent.com/r/actionssdk-4c2d9?code=7ba5wtdfaio000000000000000
&state=CsgCQUpTbDViaW5ndU54bXRNZy05X0x6QjJrRXdFcmc2WEhTZXJWSnJIRFNhV0dZOEQtR2taZFlNRTJxLTJ5eE5fbnMwVkYzc3o3M1dzUURFYUR4THZRU0xrengtbEZ5X3pzeDc1UmczT19wRDJCQlpkMWpfb054eFVTTmF6eGJIa2FvdVRhbHhJUDd3cGR1M2dfb2FUVFZpUmxEbVJvR09Bb0xscXdQWlZnTUF3eHNERzg5TGxTYmUyd2Z0TmNJTEFHQW1kYWdHRjZ0WE1fbnE5czBHNk9LdGxxdW9qY3F1czd0a2VRRGFHQlBlWnBHZDhnUEZ4OHZyZ1NrUU10aXFROXUwOE9aZHJfXzZBU09jSEtkcEhtZXhRR3U0X1U3VTZxeE9TZk5YU1lZeDBlWDNUeDlDN1BaZUhfcWp4WGFrUEZVbVdYU3d3bRIcYXNzaXN0YW50LWhhbmRvZmY6Ly9jb21wbGV0ZSI_aHR0cHM6Ly9vYXV0aC1yZWRpcmVjdC5nb29nbGV1c2VyY29udGVudC5jb20vci9hY3Rpb25zc2RrLTRjMmQ5KhthbnRvbmlvc2FwdXBwby5hc0BnbWFpbC5jb20yFGFjdGlvbnNzZGstNGMyZDlfZGV2
```
someone tell me that this url format is wrong.
however this link is generated from sample app

any ideas ?

you can try at:
https://13.93.120.183/login?client_id=117753814994818494544&redirect_uri=/frontend&state=cool_jazz

from chrome is fine
from tablet android and home app dont go

**Comment by Fleker** [comment]
So what happens when you try to authenticate through the phone?

**Comment by antoniosap** [comment]
yes.

**Comment by Fleker** [comment]
What happens? Does it not go to your website? Does it go to somewhere else instead?

**Comment by antoniosap** [comment]
from google assistant on phone

**Comment by Fleker** [comment]
Can you share a video of what happens?

**Comment by FristResponder** [comment]
it go to somewhere else instead，i met this problem

**Comment by antoniosap** [comment]
solved.
https://github.com/actions-on-google/actionssdk-smart-home-nodejs/issues/58

**Comment by FristResponder** [comment]
can you help me？how can i solve？

**Comment by antoniosap** [comment]
call @Fleker ours savior

**Comment by Fleker** [comment]
@FristResponder if you're seeing an issue, posting screenshots or better a video would help in diagnosing the error.
