### ISSUE TITLE
roomHint not working in Sync Request

### ISSUE THREAD

**Issue by honneygoyal** [actions-on-google/actionssdk-smart-home-nodejs#112]
i am sending response to sync request and device gets added but name passed in roomhint is not working.
I tried passing names given in homegraph api but none of them works.
i have tried attic, Bathroom etc. but none of them is showing up in device list.

**Comment by Fleker** [comment]
Yes, the `roomHint` parameter in the response is currently not honored.

**Comment by paulschuetz** [comment]
Does the "roomHint" field now has functionality?

**Comment by Fleker** [comment]
The `roomHint` field should now be incorporated.

**Comment by leot78** [comment]
Is it normal that the `roomHint` only works on the first SYNC and not after a Request Sync ?

When the user move a device into a new room, i trigger a RequestSync that change the `roomHint` field to a new one. Unfortunately the device is not moved to the new room in the google home app.
It looks like it only works when the user unlink and link his account.
