### ISSUE TITLE
Account linking not show

### ISSUE THREAD

**Issue by FristResponder** [actions-on-google/actionssdk-smart-home-nodejs#113]
i create a smart action，and fill information.when i tested ues the simulator,feedback "Sorry, this action is not available in simulation". when i use phone,clink the app show "Link",the screen become a little black.in a moment the screen become normal.do not show the web what can enter username and password.
i get debug information from simulator shown
"debugInfo": "https://assistant.google.com/services/auth/handoffs/auth/startaccount_name=406803663@qq.com&provider=api-ai-integration&scopes=api-ai&return_url=https://www.google.com/",
      "name": "Account Linking Url"
can you help me?
i haved another action use dialogflow,use the same account linking url,it is work well.
the Authorization URL is https://api.champontech.com/index.php/oauth/authorize/token
thank you

**Comment by FristResponder** [comment]
![8ef423ea70baadcceafc5e7d6530ff52](https://user-images.githubusercontent.com/12823785/36962006-ba754e8a-2088-11e8-8d8a-603d499745cc.jpg)

**Comment by Fleker** [comment]
Did you use Dialogflow to build this app? With the Smart Home integration, you should be able to go to the Home Control section of the Google Assistant settings and find your app.

**Comment by FristResponder** [comment]
ok,use google home app and go to the home control finded it
