### ISSUE TITLE
https://121.34.144.90 is not Local，But I don't have a domain name,how could it work?

### ISSUE THREAD

**Issue by sunjunlishi** [actions-on-google/actionssdk-smart-home-nodejs#13]
I don't want to use LAN
node cloud/smart-home-provider-cloud.js smart-home-pub="https://121.34.144.90"
it does not work,can you help me

**Comment by smishra2** [comment]
Hi @sunjunlishi , do you have any specific error message that shows when you try this?

Could you try running

`node smart-home-provider-cloud.js smart-home-pub="https://121.34.144.90"`

(remove the `cloud/` at the beginning)

**Comment by sunjunlishi** [comment]
ok ,i will have try,but it is not import ye.because i have know your code,thank you
