### ISSUE TITLE
how to response?

### ISSUE THREAD

**Issue by sunjunlishi** [actions-on-google/actionssdk-smart-home-nodejs#14]
![http](https://user-images.githubusercontent.com/11845664/28003304-49aa3a82-656f-11e7-9bee-c7531653b4e3.png)

can you help me,how to response; http style

**Comment by smishra2** [comment]
Hi @sunjunlishi , can you clarify what response you are confused about? Have you been able to check the sample and get it to work w/ this flow?

**Comment by sunjunlishi** [comment]
ok i have resolve it
![qq 20170711111936](https://user-images.githubusercontent.com/11845664/28049587-ef062cf0-662a-11e7-998a-921cca1f6102.png)

**Comment by sunjunlishi** [comment]
i have receive devices.SYNC,but i not know how to response sync devices

**Comment by sunjunlishi** [comment]
Does this right？
![qq 20170711112322](https://user-images.githubusercontent.com/11845664/28049684-730190f8-662b-11e7-99ee-36f1be3d5b51.png)

**Comment by sunjunlishi** [comment]
and use your demo slyle,not ok too
  * {

   *  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",

   *   "payload": {

   *     "devices": [{

   *         "id": "123",

   *         "type": "action.devices.types.Outlet",

   *         "traits": [

   *            "action.devices.traits.OnOff"

   *         ],

   *         "name": {

   *             "defaultNames": ["TP-Link Outlet C110"],

   *             "name": "Homer Simpson Light",

   *             "nicknames": ["wall plug"]

   *         },

   *         "willReportState: false,

   *         "attributes": {

   *         // None defined for these traits yet.

   *         },

   *         "roomHint": "living room",

   *         "config": {

   *           "manufacturer": "tplink",

   *           "model": "c110",

   *           "hwVersion": "3.2",

   *           "swVersion": "11.4"

   *         },

   *         "customData": {

   *           "fooValue": 74,

   *           "barValue": true,

   *           "bazValue": "sheepdip"

   *         }

   *       }, {

   *         "id": "456",

   *         "type": "action.devices.types.Light",

   *         "traits": [

   *           "action.devices.traits.OnOff",

   *           "action.devices.traits.Brightness",

   *           "action.devices.traits.ColorTemperature",

   *           "action.devices.traits.ColorSpectrum"

   *         ],

   *         "name": {

   *           "defaultNames": ["OSRAM bulb A19 color hyperglow"],

   *           "name": "lamp1",

   *           "nicknames": ["reading lamp"]

   *         },

   *         "willReportState: false,

   *         "attributes": {

   *           "TemperatureMinK": 2000,

   *           "TemperatureMaxK": 6500

   *         },

   *         "roomHint": "living room",

   *         "config": {

   *           "manufacturer": "osram",

   *           "model": "hg11",

   *           "hwVersion": "1.2",

   *           "swVersion": "5.4"

   *         },

   *         "customData": {

   *           "fooValue": 12,

   *           "barValue": false,

   *           "bazValue": "dancing alpaca"

   *         }

   *       }, {

   *         "id": "234"

   *         // ...

   *     }]

   *   }

   * }

**Comment by sunjunlishi** [comment]
ok,i console the  json info
{ 
"requestId": "10525247228645671761",
	"payload" : 
	{ "devices": 
		   [
		   { "type": "action.devices.types.LIGHT",
			   "traits" :
			   ["action.devices.traits.OnOff",
			   "action.devices.traits.Brightness",
			   "action.devices.traits.ColorTemperature",
			   "action.devices.traits.ColorSpectrum"],
			   "name" :
		   { "defaultNames": ["Smart Light"],
			   "name" : "Smart Light 2",
			   "nicknames" : ["doorway"] },
			   "willReportState" : false,
			   "roomHint" : "living room",
			   "deviceInfo" :
		   { "manufacturer":"Smart Home Provider",
			   "model" : "g1337",
			   "swVersion" : "1.0.11",
			   "hwVersion" : "1.0" },
			   "customData" : { "smartHomeProviderId": "FkldJVJCmDNSaoLkoq0txiz8Byf2Hr" },
			   "id" : "2" }

		   ] 
	}
}

it works now,thank you
