### ISSUE TITLE
REQUEST_SYNC error

### ISSUE THREAD

**Issue by i8beef** [actions-on-google/actionssdk-smart-home-nodejs#18]
I noticed that you added pieces to trigger a request_sync through a homegraph api... but when I attemp to trigger these calls against my instance, I get the following: 

Google HomeGraph API has not been used in project homeautio-1c61c before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/homegraph.googleapis.com/overview?project=XXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Clicking that link says "The API "homegraph.googleapis.com" doesn't exist or you don't have permission to access it".

Did I fail to enable something or miss a step?

**Comment by c4xuange** [comment]
The HomeGraph API is not public yet

**Comment by i8beef** [comment]
Well that sucks. I was kind of hoping you'd direct me to some super secret "enable it here" page... :-)

I'll continue checking for it to go public then every couple of days.

**Comment by asturel** [comment]
Its "public" now, the device resync works flawlessly.

**Comment by i8beef** [comment]
Thanks, I actually saw this and have already implemented on my side. Works so far!
