### ISSUE TITLE
Can't deploy actions package

### ISSUE THREAD

**Issue by technology20nn** [actions-on-google/actionssdk-smart-home-nodejs#2]
I clone project to localhost.
I go to console.actions.google to create project. I go to folder project (it have file actions.json) and  run command "gactions update --action_package action.json --project <project_name>". It has error:

ERROR: Failed to update the app for the Assistant
ERROR: Invalid JSON payload received. Unknown name "device_control" at 'agent.draft_action_package.actions[0]': Cannot find field.
Field Violations:
#  Field                                  Description
1  agent.draft_action_package.actions[0]  Invalid JSON payload received. Unknown name "device_control" at 'agent.draft_action_package.actions[0]': Cannot find field.
2017/05/26 22:03:21 Server did not return HTTP 200

Please fix this. :(

**Comment by siburny** [comment]
Same problem here

**Comment by asturel** [comment]
just remove that:

`"deviceControl": { },`

in action.json, then it will work.

**Comment by siburny** [comment]
I can confirm that it works now. Yesterday, removing `deviceControl` produced a different error.

**Comment by Kant73** [comment]
Same problem here too, removing `"deviceControl": { },` fix it thanks :)

**Comment by siburny** [comment]
Removing `deviceControl` produced a different error initially. It works fine now without it.
