### ISSUE TITLE
gactions update timeout 

### ISSUE THREAD

**Issue by dooyawoo** [actions-on-google/actionssdk-smart-home-nodejs#21]
I want to try uploading the sample action package I have using gactions. However, every time I execute this command:
`./gactions update --action_package action.json --project smarthomedev-74b08`
the reuslt always like this:
`Post https://accounts.google.com/o/oauth2/token: dial tcp 172.217.27.141:443: i/o timeout`

**Comment by Fleker** [comment]
Try following the advice in this [SO question](https://stackoverflow.com/questions/45340903/update-action-package-with-gactions-always-returns-request-timeout)

* Try switching to a different connection
* Delete `creds.data`
* Get a new authorization code

**Comment by dooyawoo** [comment]
Thanks! It's My VPN problem
