### ISSUE TITLE
I'm sorry, there was an error and I'm unable to control your home device.

### ISSUE THREAD

**Issue by dooyawoo** [actions-on-google/actionssdk-smart-home-nodejs#24]
Using Simulator, responds with a generic message:"I'm sorry, there was an error and I'm unable to control your home device."  I don't get any other commands on my server.
I test scene by mock-assistant-platform and its ok!
Mock logs
<img width="1269" alt="23" src="https://user-images.githubusercontent.com/6778877/29237672-b58b3968-7f55-11e7-8b69-e6785924fe3f.png">

Devices and Scenes shown in Google Home
![img_0296](https://user-images.githubusercontent.com/6778877/29237575-cb6e39ee-7f53-11e7-85a2-540aa33c2861.JPG)
Respond
![12](https://user-images.githubusercontent.com/6778877/29237590-118148a4-7f54-11e7-9ae3-3798c4df9b7a.png)

**Comment by Fleker** [comment]
Are you running this locally? Have you updated your action package and run
gactions year to use the new endpoint?

**Comment by dooyawoo** [comment]
Its running on my server  and has already been updated

**Comment by dooyawoo** [comment]
@Fleker Is there a limit to the device id length? My device id likes 569A424B000135vwr4ts8ustdykcqkpj9n. Similarly, what is the limit to name and defaultNames?

**Comment by entertailion** [comment]
There aren't limits for these. We suspect you might be running into an auth issue, likely a token that you aren't refreshing correctly. Please take a look at our FAQ that was updated recently: https://developers.google.com/actions/smarthome/faq

**Comment by dooyawoo** [comment]
@entertailion It's ok! Just need to refresh twice.Does Google have plans to support curtain motor?
Our products are curtain motor，User usage commands such as open and close.I tested the close command is ok，but the open is not ok!
<img width="405" alt="1" src="https://user-images.githubusercontent.com/6778877/29352472-5681f8e8-8299-11e7-9a78-649e81c18b47.png">

**Comment by entertailion** [comment]
I have forwarded your request for a blinds trait to the Smart Home team. Closing this issue, since it looks like you have things working with the current traits.
