### ISSUE TITLE
Test Action/App not visible in Home Control Section of Google Home

### ISSUE THREAD

**Issue by marziman** [actions-on-google/actionssdk-smart-home-nodejs#25]
Hello Google-Devs,

this issue was closed, but is still an issue and NOT solved.
After having several email conversations with Google support (since weeks) and alot of developer complaints about this @Fleker closed this issue by saying it is not a specific issue.
I dont think that this is the case and dont want to stress you guys, but you have an issue here and should track it transparently. I am not sure who is the lead for the actions on google smarthome project at Google, but I hope @smishra2 will read this and escalate this somehow.

Actually you are blocking a lot of Devs by not solving this. This cant be your strategic target in beating platforms like Amazon Alexa. So please take this issue here serious.
At the moment it looks like you re not actively clearing this issue out.

I am sorry for re-opening, but we need help form your side. Or the people wont create more smarthome apps, I guess.

I also filed an question on Stackoverflow with full description, like the support asked me to do:
https://stackoverflow.com/questions/45234171/smarthome-app-action-doesnt-appear-in-google-assistant-companion-app-under-home

Hope Google will react and solve this..what ever problem this is. I guess this cant be rocket sience and the experts at Google can fix this.

BR Mehmet

**Comment by Fleker** [comment]
Good afternoon,
I'm on vacation this week, finding a time when I can visit my family and grandmother. We are looking at specific user cases. Please use [the support form](https://developers.google.com/actions/support/) and include your project id and associated email address you're seeing a problem with to help us triage the issues. Others will be able to follow up this week.

**Comment by paresy** [comment]
We have the same problem. Support ticket sent.

**Comment by asturel** [comment]
On my phone the whole "Home Control" (?) menu is gone, but the voice actions still works. Only way to go to home control is 'help me with home control' voice action :/ but my app is no longer listed

**Comment by marziman** [comment]
I will close this. Google Devs (thx to @Fleker ) made some changes on the platform. I can see now my action in the app, but ran into another known issue https://github.com/actions-on-google/actionssdk-smart-home-nodejs/issues/26
