### ISSUE TITLE
Why need create an API KEY?

### ISSUE THREAD

**Issue by lukunnr** [actions-on-google/actionssdk-smart-home-nodejs#27]
Hi ;
I really don't understand what it's like to create a project on Google cloud and generate an API key.
I didn't find out where he was being use it , I see that the code only checks to see if API KEY is filled in, and does not check any validity?
---------------------------------------------------------------------------------------------------------
Click Credentials
Click 'Create credentials'
Click 'API key'
Copy the API key shown and insert it in smart-home-provider/cloud/config-provider.js
---------------------------------------------------------------------------------------------------------

**Comment by Fleker** [comment]
Yes the code just checks the existence of an API key. One can assume that a
developer using the sample may forget to fill in the API key. But if they
do, it's probably correct since they followed the steps. It's assumed to be
valid. If not, the server will return an authentication error.

**Comment by lukunnr** [comment]
I see. Thanks for the answer.
