### ISSUE TITLE
Couldn't link account in Google Home companion app

### ISSUE THREAD

**Issue by mwidlok** [actions-on-google/actionssdk-smart-home-nodejs#28]
Hi,
when I'm using Google Home App on iOS, I'm able to display login form within my system when using Home Control -> Add devices.
Then after successful login I get "Something went wrong. Try Again"
No SYNC call received in API.

I've checked this on two different google accounts, in two different actions on google Assistant apps. Redirects are properly set in my oauth.

**Comment by Fleker** [comment]
This is the same as issue #26. Triaging into that.
