### ISSUE TITLE
Cloud icon resets on refresh of page

### ISSUE THREAD

**Issue by dermotos** [actions-on-google/actionssdk-smart-home-nodejs#29]
The cloud Icon on the frontend page resets to off upon refreshing the page. I can still ask Google to turn it on/off, and she does so, however the page does not update. 
I see the following error on the `smart-home-provider-cloud.js` output:

`(node:67629) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Device 1 unknown to Amce Cloud`

**Comment by Fleker** [comment]
What is the order of operations between opening the web UI, linking your account in the app, and executing commands through the Assistant?

**Comment by dermotos** [comment]
Sorry, I thought I already responded. I followed all steps in the `readme.md` and setup the project without issue. Any refresh of the page causes the state not to be displayed correctly.

eg: After a successful setup after following the steps in the readme, naming the first device `red lamp` and clicking the cloud icon, I can successfully ask Google to "turn on the red lamp". 

Then, if I refresh the page, the lamp indicator returns to the `off` state and the cloud icon shows disabled again. I can still ask google "is the red lamp on?" and it replies "yes".

If I subsequently ask Google to turn on the red lamp again, it tells me it succeeded, however the web page doesn't update.

**Comment by Fleker** [comment]
Okay thanks for letting me know. Does light triggering work on the webpage if you enable the cloud icon again?

**Comment by dermotos** [comment]
Yes

**Comment by Fleker** [comment]
This seems like we'd benefit from having the ability to force a resync on the server each refresh to obtain the latest states.
