### ISSUE TITLE
Unable to Share Smart Home Action on Google With Other Accounts

### ISSUE THREAD

**Issue by AlexSneedMiller** [actions-on-google/actionssdk-smart-home-nodejs#30]
Using my Primary Google Account I am able to follow the instructions in the [readme](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/README.md) to spin up my own node.js server and a new Project via the Actions SDK. I am able to open up my Google Home app (Android) and link the 4 light bulb devices under the rick:oldman account and everything works great.

Then I tried to add my Secondary Google Account to the project by granting it Project Viewer access in the permissions, and then sharing the link from the Simulator to that account. I open up the Google Home app for this other account (iPhone) and log in with the beth:doctor account.  Then instead of showing me the lights that are available I get an error that says "Something went wrong. Try again": [Screenshot](https://image.ibb.co/douANQ/google_home_error.png)

I then deleted the project from my Primary Google Account, but I still see the "[test]" Smart Home service when I click on the "+" to add a new device on my Google Home app on my Android phone with my Primary Google Account, and on my iPhone with my Secondary Google Account.  When I first saw this I just unlinked my account. Now I am still seeing it and when I press on it to see what happens, it says "Tunnel xxxxx.ngrok.io not found". Does this mean that AoG still thinks that this is active? Maybe it takes some time for everything to sync up with the fact that the project has been shut down, or maybe I've gotten myself stuck in some strange edge case? 

Some more weird stuff...In addition to my real light bulbs, I have 4 lights under the "Virtual and other devices" category (I assume from a past test of this AoG Smart Home app) and I can't seem to get rid of them.

**Comment by Fleker** [comment]
When you share the project, does it work on their account with rick:oldman? Can you grant them Project Owner access and see if it works?

When did you run the test and when did you see this issue? It may take up to three days for agents to expire. Can you wait three days or so and see if the problem persists?

**Comment by AlexSneedMiller** [comment]
It gave me the same error when I used rick:oldman as well. I will wait a few days and try again.


I started over from scratch with my Secondary Google Account, which is on my iPhone. I spun up the node.js app and set up the AoG with the Actions SDK. When I clicked on "Test Draft" it appeared to work just fine. I opened up my Google Home app on my iPhone, but there was no way for me to add a device it seems, when I click "+ ADD NEW DEVICE" (hamburger menu -> Devices -> "+ ADD NEW DEVICE" ) it wants me to disconnect my wifi to a different wifi network as if it's just trying to set up a new Google Home or Chromecast. I've seen this before, but I was able to get to a screen where I could link my account to the AoG Smart Home app, but for some reason I can't seem to get back to that page. I think in the past I had clicked on a link from the 'Discover' tab in the iOS app (There is no "Home control" option). I have never run into this problem with my Primary Google Account on my Android phone.

I was able to share this project with my Primary Google Account (originally as an owner, then removed it and re-added it as just a viewer) and it worked fine on my Android phone.

**Comment by Fleker** [comment]
On Android, adding a Smart Home device should be in hamburger menu -> "Home Control". Is it different on iOS?

**Comment by AlexSneedMiller** [comment]
On my Primary Account the Google Home app on iOS it looks like it does on Android as you've described. When I switch over to my Secondary Account on my iPhone the hamburger menu looks different and it does not have the "Google Assistant" section in the menu: [Screenshot](https://image.ibb.co/fMN9XQ/HOMEios.png)

**Comment by AlexSneedMiller** [comment]
@Fleker are you able to be part of two test AoG Apps? One of my accounts is still showing an old project that was deleted (the 3 days hasn't been up yet), but I don't see the new app I just created in the list of providers in the Google Home app.

**Comment by AlexSneedMiller** [comment]
I made a new app on my Secondary Account and used a completely new Android device. I got to the login screen and logged in with rick:oldman, but I still got the "couldn't update the setting" error.

Everything looks good on my node server logs, is there any way to get more information from the Google Home app as to why it wouldn't be working?

**Comment by Fleker** [comment]
The "couldn't update the setting" issue is related to #26.

The inability to find your test apps is related #25 which does appear to be still affecting a small number of developers. But it does seem like you're slightly past that point.

**Comment by AlexSneedMiller** [comment]
I'm still seeing a bunch of "Virtual and other devices", even though I have unlinked my test smart home app account. Should the Google Home app know that I am no longer connected to my test app and remove those devices? It's been nearly two weeks since I've last has the ngrok server up that hosted those virtual devices.

I am still not able to share a project with another account from my primary account, even when I make it an owner. I"m not sure if this is related to #25 or not though.

**Comment by Fleker** [comment]
Can you try [the Google Assistant](https://itunes.apple.com/us/app/google-assistant/id1220976145?mt=8) app? It should have a Home Control section. It shouldn't be related to #25.

**Comment by AlexSneedMiller** [comment]
When I try and update my oauth settings (new ngrok URL, etc.) I am getting this generic error when I press "save". When I open the developer tools I see there is a 500 response when my browser does a POST to https://console.actions.google.com/u/0/m/actions/agents/update

```
)]}'

[["er",null,"java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.\n\tat com.google.assistant.serviceengine.acs.server.proto.ActionsConsoleAgentSettingsPB$AgentType.getNumber(ActionsConsoleAgentSettingsPB.java:165)\n\tat com.google.assistant.serviceengine.acs.server.proto.ActionsConsoleAgentSettingsPB$Builder.setAgentType(ActionsConsoleAgentSettingsPB.java:696)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleAgentSettingsConverter.doForward_agentType(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleAgentSettingsConverter.java:20)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleAgentSettingsConverter.doForward(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleAgentSettingsConverter.java:41)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleAgentSettingsConverter.doForward(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleAgentSettingsConverter.java:12)\n\tat com.google.common.base.Converter.correctedDoForward(Converter.java:183)\n\tat com.google.common.base.Converter.convert(Converter.java:176)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter$1.lambda$apply$0(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.java:34)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1375)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\tat java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter$1.apply(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.java:35)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.doForward_actionsConsoleAgentSettings(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.java:37)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.doForward(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.java:42)\n\tat com.google.assistant.aog.console.server.main.AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.doForward(AutoConverter_ActionsConsoleSettingsConverter_ActionsConsoleSettingsPBConverter.java:17)\n\tat com.google.common.base.Converter.correctedDoForward(Converter.java:183)\n\tat com.google.common.base.Converter.convert(Converter.java:176)\n\tat com.google.assistant.aog.console.server.main.ActionsConsoleSettingsConverter.toServer(ActionsConsoleSettingsConverter.java:21)\n\tat com.google.assistant.aog.console.server.main.AgentConverter.toServer(AgentConverter.java:383)\n\tat com.google.assistant.aog.console.server.main.UpdateAgentAction.post(UpdateAgentAction.java:89)\n\tat com.google.assistant.aog.console.server.main.AssistantConsoleExceptionInterceptor.execute(AssistantConsoleExceptionInterceptor.java:24)\n\tat com.google.apps.framework.request.impl.InterceptorInvocation$Http.beforeProceed(InterceptorInvocation.java:125)\n\tat com.google.apps.framework.request.impl.InterceptorInvocation.proceed(InterceptorInvocation.java:157)\n\tat com.google.apps.framework.request.impl.NewfangledHttpDispatcher.proceed(NewfangledHttpDispatcher.java:73)\n\tat com.google.apps.framework.request.impl.NewfangledHttpDispatcher.proceed(NewfangledHttpDispatcher.java:31)\n\tat com.google.apps.framework.request.impl.AbstractDispatcher.doExecuteChain(AbstractDispatcher.java:364)\n\tat com.google.apps.framework.request.impl.AbstractDispatcher.execute(AbstractDispatcher.java:261)\n\tat com.google.apps.framework.request.impl.AbstractDispatcher.executeAsync(AbstractDispatcher.java:206)\n\tat com.google.apps.framework.request.impl.NewfangledHttpDispatcher.dispatch(NewfangledHttpDispatcher.java:60)\n\tat com.google.apps.framework.net.NewfangledHttpRequestRunner.handle(NewfangledHttpRequestRunner.java:36)\n\tat com.google.apps.framework.net.HttpServiceImpl$RequestHandler$3.run(HttpServiceImpl.java:225)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)\n\tat com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:297)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:320)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:312)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat com.google.apps.framework.server.AbstractThreadPoolModule$InitializingThreadFactory$1.run(AbstractThreadPoolModule.java:581)\n\tat java.lang.Thread.run(Thread.java:745)\n",null,null,500,null,null,null,13]
]
```


![image](https://user-images.githubusercontent.com/3960615/30647982-84d17818-9de2-11e7-953f-b64f1acf5432.png)


Sorry if this is not the best way to report this. Let me know if I should send it somewhere else or open a new issue in this repo.

**Comment by Fleker** [comment]
@AlexSneedMiller can you make a new issue for this? In the meantime I'll check to see if anything broke.

**Comment by AlexSneedMiller** [comment]
This morning when I tried it appeared to be fixed, but I opened a new issue anyways #39

**Comment by AlexSneedMiller** [comment]
Is there a limit to the number of test Smart Home Apps you can have on your account? I was able to create a Smart Home App individually on two different Google accounts, but when I tried to share one of them with the other I did not see the second Smart Home App show up in the list of new Linked Services. 

I even went so far as to remove the privileges of one of the Smart Home Apps; I would think that would force the Linked Service to not show up at all in my Google Home app, but it still does show up. Is this something that takes a while to propagate through the system? Earlier in this thread @Fleker mentioned it can take up to 3 days for an agent to disappear. Does "agent" refer to the service, or the devices that were linked through that service?

I am still seeing old 'virtual devices' under my account for projects that I have deleted weeks ago.

**Comment by Fleker** [comment]
Users can only test one "agent" per account. That test agent will last three days before it "expires" and needs to be re-tested. If you create multiple projects, only one will be active. However, when they expire it does not delete devices. All your devices will still be registered just not active.

**Comment by AlexSneedMiller** [comment]
Ah that makes sense, thank you! Sorry if that's in the documentation somewhere and I haven't seen that yet. I will wait three days and then share the Smart Home App from my main account to the other users. 

Is there a way to delete the devices so they don't show up? When I ask Google to turn on my lights it turns on the few that I have, and then says there was an error with the other 6 that are 'virtual'.

**Comment by Fleker** [comment]
Test agents should be chronologically determined, ie. testing a new one will disable the previous one.

I'm not sure how to remove devices. I was pretty sure there was an option for that in the app, but I just checked and it's not there. 🤔

**Comment by AlexSneedMiller** [comment]
Adding a new project to my account and clicking on 'Test Draft' did seem to kick out the old agent. When that happens, is there a process for the Home Graph to sync it's own list of devices with the agents I have in my account? I wonder if I did test a new draft and never unlinked the old account originally.

I have tried to unlink my test agent/app. Let me know if you need further access to anything for debugging.

**Comment by Fleker** [comment]
There's no hook currently for the HomeGraph to resync when your list of connected agents change. You will need to use the Google Home app to unlink current agents and link new ones.

**Comment by AlexSneedMiller** [comment]
I have unlinked my test agent, but the "virtual and other devices" still show up in my "Devices" tab in Home Control.

**Comment by Fleker** [comment]
That's probably a bug in the Home app. Can you control your devices?

**Comment by AlexSneedMiller** [comment]
I am able to control my real devices. When I do control them (I have 2 real light bulbs, and 4 virtual/fake light bulbs) it says something along the lines of "I was able to turn on two lights, but I was not able to turn on 4 lights"

**Comment by Fleker** [comment]
I'll follow up on that Home bug.
