### ISSUE TITLE
Home Control Action won't work anymore

### ISSUE THREAD

**Issue by himicc** [actions-on-google/actionssdk-smart-home-nodejs#34]
We've developed a Home Control Action (project id: smart-life-da-b0b7c), which is still under testing environment. It worked well at the beginning, we could discover the device and control it with no problem. But recently, about 1 week ago, the Action came up with this issue: "Couldn't update setting. Check your connection". We didn't change anything for our service, we just can't receive the SYNC request after the token exchange. Need help pls.

**Comment by Fleker** [comment]
You can use #26 for collecting the problem. Are you still in testing mode? Test agents expire after 3 days. Sorry to hear your problem has been recent. You can [email me](mailto:fleker@google.com) your project id and email you used.
