### ISSUE TITLE
Lights'/outlets' status in French (France)

### ISSUE THREAD

**Issue by BenjaminBertran** [actions-on-google/actionssdk-smart-home-nodejs#35]
Don't know if it's the right place for this issue but something goes wrong with the French (France) version when we ask the status of lights or the outlets (in certain conditions). I've checked the QUERY request/response and everything is ok, it works with (at least) French (Canada) and English (US), not tried the other ones.

In short, it only works if we ask the status for less than 3 lights or outlets in THE SAME STATUS. 

Examples translated in english to be understood (this is the same for outlets):

- A single light, targeted by name: 
 -> It works, whatever the state: "Light 1 is on" or "Light 1 is off": OK

- 3 lights (Light 1, 2 and 3):
 -> If 2 are on and 1 off, the answer is "Light 1 and Light 2 are on. Light 3 is off": OK
 -> If 1 are on and 2 off, the answer is "Light 1 is on. Light 3 and Light 2 are off": OK
 -> If all lights are on or off, silence... no answer at all.

- 4 lights (Light 1, 2, 3 and 4):
 -> It only works if 2 devices are on and 2 are off.
 -> No answer in other cases.

**Comment by Fleker** [comment]
Thanks for mentioning this. I will be sure to forward to the appropriate team.

**Comment by Fleker** [comment]
Have you been able to try this with smart lights/outlets that already exist, or just ones you've created in your smart home app?

**Comment by BenjaminBertran** [comment]
I've tried both: 
- only with our devices
- a mix with our devices and a Lifx
... same issue.

**Comment by Fleker** [comment]
A bug was filed on this a while ago, so the issue will be closed.

**Comment by Fleker** [comment]
@BenjaminBertran can you provide the exact French text of what you're saying?

**Comment by BenjaminBertran** [comment]
Hi, it seems the bug was fixed few weeks ago, there's no more problem in French. Thanks!
