### ISSUE TITLE
I'm sorry, there was an error and I'm unable to control your home device.

### ISSUE THREAD

**Issue by dooyawoo** [actions-on-google/actionssdk-smart-home-nodejs#37]
Using Simulator, responds with a generic message:"I'm sorry, there was an error and I'm unable to control your home device." I don't get any other commands on my server.
An interesting phenomenon。When synchronizing my device，the first time always fails，then got an error: "Couldn't update the settings. Check your connection"。Immediately synchronize for the second time，It’s OK！

**Comment by Fleker** [comment]
This only happens using the simulator? Can you send the same command on your phone and see if it works?

Are you trying a general query, ie. "Turn all my lights on" or specifically to one device "Turn my lamp on"?

**Comment by dooyawoo** [comment]
Google Assistant also has the same problem.The command "Turn all my lights on" or  "Turn my lamp on" also fails.

**Comment by AlexSneedMiller** [comment]
Not sure if this will help at all...but I got the same error when I had everything correct (including oauth URLs) except for the url in my action package. If you're using this node.js app to host your devices the default path for conversations.automation.url is the "/ha" path https://a1234567.ngrok.io/ha

**Comment by dooyawoo** [comment]
@AlexSneedMiller Thanks!The SYNC is OK!Only failed for EXEC

**Comment by Fleker** [comment]
Seems like there's two separate things happening here. The error message with SYNC is probably benign. Why is it not executing though? Is your SYNC response not providing enough information to correctly handle the execution command?

**Comment by Fleker** [comment]
This could be related to #58 or is now fixed.
