### ISSUE TITLE
Upload it on Heroku ?

### ISSUE THREAD

**Issue by Kinjalk** [actions-on-google/actionssdk-smart-home-nodejs#4]
I tried uploading this repo to Heroku but it didn't work. It is working on local Host though. Please can you guide me with proper steps to upload the repo ?  Which files should I upload ?

**Comment by Fleker** [comment]
What part of this repo are you intending to send to Heroku?

**Comment by pantongren** [comment]
Hi,sir. How to host the project to Firebase or Google Cloude Platform. if I choose your repo as my template,what part of this repo I need to insert to my project which should be uploaded to Firebase or Google Cloud Platorm?

**Comment by Fleker** [comment]
The `smart-home-provider` contains all the code that one's cloud needs to run as well as a frontend for creating and changing virtual devices.
