### ISSUE TITLE
Smart Home Intents mixed with other Intents

### ISSUE THREAD

**Issue by futbolpal** [actions-on-google/actionssdk-smart-home-nodejs#40]
This is more of a question, but I was thinking of creating an app that could service Smart Home Intents (/ha) and also Google Action intents (/ga).  (https://github.com/futbolpal/harmony-home).
I  have a `home-automation` branch that adds Smart Home functionality.

This way I could use the smart home style (which is less verbose, no "tell to so-and-so to do X"), but also support things that aren't supported by smart home (since there is only two schemas).

In the repo, I'm using some scripts to generate action.json based on environment variables (from Heroku for example).  I was hoping to use one action.json with intents for action.intents.devices and others, **however**, it appears that a smart home intent must be the only intent in the action.json.

Any thoughts on this?  It's kind of a bummer, but at the minute, I could basically create two apps and two sets of action.js files that I could push out in a deploy pipeline.

**Comment by Fleker** [comment]
Yeah for right now Smart Home and AoG projects need to be separated.

**Comment by futbolpal** [comment]
Thanks :/
