### ISSUE TITLE
SYNC error after login:could not change settings, please check your connection

### ISSUE THREAD

**Issue by bzhang222** [actions-on-google/actionssdk-smart-home-nodejs#41]
I have my own OAuth2, which worked with  Alexa and others.  For Google SYNC command after login to OAuth2 server and exchange token, it does send me the SYNC command with my bearer token, here is my response to the google server. Somehow after I response to google, it quickly flash an error "could not change settings, please check your connetion..." It was so fast that I have to do many times to read the line, anyways here is the log from my side, since my app is not published yet, I can't get log from google console -- please help 
thanks
Bill

"inputs":[{"intent":"action.devices.SYNC"}],"requestId":"2616915316542317627"}
017-09-23 17:26:32,499 root         DEBUG    GOOGLE:receives a SYNC request 2616915316542317627 2017-09-24 00:26:32.49800
017-09-23 17:26:33,005 root         DEBUG    Get out SYNC 2017-09-24 00:26:33.005000
017-09-23 17:26:33,009 root         DEBUG    {"requestId": "2616915316542317627", "payload": {"agentUserId": "1234", "devices": [{"customData": {"guid": "9a73dc90-5068-442e-96b0-a8314d3bdf44", "serialNo": "P823E6Y6KEU64LN6WR4UN354Y6BP28HLAXR6KL", "fooValue": 74, "id": 45}, "deviceInfo": {"model": "hs1234", "swVersion": "11.4", "hwVersion": "3.2", "manufacturer": "dda"}, "willReportState": false, "traits": ["action.devices.traits.OnOff"], "names": {"defaultNames": ["Device One"], "name": "Device One", "nicknames": ["Device One"]}, "type": "action.devices.types.OUTLET", "id": "9a73dc90-506-442e-96b0-a8314d3bdf44"}]}}
017-09-23 17:26:33,017 werkzeug     INFO     10.0.0.6 - - [23/Sep/2017 17:26:33] "POST /googleop/ha HTTP/1.1" 200 -

**Comment by Fleker** [comment]
It's not an issue with your OAuth server. Taking a look at your JSON response. You have the device names all nested in a `names` key. That is a typo, it should be `name`, singular.

The error message is a bit unhelpful unfortunately, but this answer should unblock you.

**Comment by bzhang222** [comment]
Thanks a lot for promptly look into the issue; Really appreciate you answering the email over weekend.
