### ISSUE TITLE
App launch failing in actions console

### ISSUE THREAD

**Issue by vppillai** [actions-on-google/actionssdk-smart-home-nodejs#43]
Hi,
 I tried following the steps here and when I click the "Test Draft" button, I get an error stating "start test failed". There are no error messages thrown in the console. 

 I am able to launch the webApp. So, I believe that my setup and tunneling is working fine.

**Comment by Fleker** [comment]
Can you SYNC through the Home app on your phone?

**Comment by vppillai** [comment]
nope! :(

**Comment by Fleker** [comment]
Can you see your test project in the Home Control section of the Home app on your phone?

**Comment by vppillai** [comment]
yes

**Comment by Fleker** [comment]
So you go through the account linking process on your phone: open your test project, link your account, successfully authenticate, but then get an error message when you try to sync devices?

**Comment by vppillai** [comment]
Yes, That was the case for more than 4 days straight. But it seems to have resolved itself now. Looks like there was some backend issue?

**Comment by Fleker** [comment]
Yeah I'd imagine there was some server-side issues that are being resolved slowly.
