### ISSUE TITLE
Unlink/Link needed every day

### ISSUE THREAD

**Issue by jenskastensson** [actions-on-google/actionssdk-smart-home-nodejs#45]
I can sync and send commands to my devices with my GH action. 
But the day after, I always get "I'm sorry, there was an error and I'm unable to control your home device."
Nothing is sent to the handler. 
When I unlink the service and link it again all works as expected.
How can I troubleshoot this problem?

**Comment by Fleker** [comment]
Test agents expire frequently, meaning you need to redo account linking. It's supposed to expire after three days.
