### ISSUE TITLE
Sync stopped working

### ISSUE THREAD

**Issue by pevecyan** [actions-on-google/actionssdk-smart-home-nodejs#48]
Hi, today I tried to connect to our Smart Home action but sync fails every time. We receive the request and our response seems to be OK. Were there any changes made on required information in response since Friday?

**Comment by Fleker** [comment]
I don't believe anything changed. Can you confirm your sync response is correctly formatted?

**Comment by Fleker** [comment]
We just launched a [SYNC validation tool](https://developers.google.com/actions/smarthome/tools/validator/) to check your responses and verify that they're correctly formatted.

**Comment by vibgy** [comment]
Please make sure refreshing access token using the /token API is working for you.

**Comment by Fleker** [comment]
Closing this issue. If the problem persists, please see the triage issue #58
