### ISSUE TITLE
How to setup ssl

### ISSUE THREAD

**Issue by thuongtin** [actions-on-google/actionssdk-smart-home-nodejs#5]
How to setup ssl?

**Comment by weihao042122** [comment]
need ssl

**Comment by Fleker** [comment]
What part of SSL are you looking to implement? The server-side Node.JS code should run on a server with SSL.

**Comment by Canain** [comment]
Hi @thuongtin and @weihao042122 ,

The sample uses a basic Node.js [Express](https://expressjs.com/en/api.html) server to host the endpoints and [uses the PORT environment variable to specify the app port](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/cloud/smart-home-provider-cloud.js#L426)

This means that if you deploy it to most cloud services like Google Cloud Functions, AWS, or Heroku, they can automatically specify the port and use reverse proxies to serve SSL content sourcing from the Express server automatically for you.

If you want to deploy SSL yourself, you would need to first [generate a cert](https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs) and then use [https.createServer](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) to create the server using the Express `app` variable as the handler.

Here's a code sample of how that would look like which is similar to the Node.js [https reference](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) when implemented using this sample:
```javascript
const https = require('https');
const fs = require('fs');
const express = require('express');

const config = require('./config-provider');

const options = {
  key: fs.readFileSync('/path/to/key.pem'),
  cert: fs.readFileSync('/path/to/cert.pem')
};

const app = express();

const appPort = process.env.PORT || config.devPortSmartHome;

const server = https.createServer(options, app).listen(appPort, () => {
  const host = server.address().address;
  const port = server.address().port;
  console.log('Smart Home Cloud and App listening at %s:%s', host, port);
});
```

The listen portion of the code should replace the [lines at and below here](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/cloud/smart-home-provider-cloud.js#L426)

In short, add these requires in [this file](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/cloud/smart-home-provider-cloud.js)
```javascript
const https = require('https');
const fs = require('fs');
```

And replace [this line](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/cloud/smart-home-provider-cloud.js#L426)
```javascript
const server = app.listen(appPort, function () {
```
with
```javascript
const options = {
  key: fs.readFileSync('/path/to/key.pem'),
  cert: fs.readFileSync('/path/to/cert.pem')
};
const server = https.createServer(options, app).listen(appPort, () => {
```

The `listen` method should be identical to Express's `app.listen` as explained [here](https://expressjs.com/en/api.html#app.listen)

**Comment by Canain** [comment]
Let me know if you have more questions or if it doesn't work.
