### ISSUE TITLE
add windSpeed attribute to Thermostat

### ISSUE THREAD

**Issue by JudyHsiao** [actions-on-google/actionssdk-smart-home-nodejs#52]
Hi,
Is there any possibility to support wind speed attribute for thermostat?
Thanks for your  answering.

**Comment by Fleker** [comment]
Your use case would be a thermostat that is providing details about the external environment?

I think it probably wouldn't fit in the Thermostat device type, but a future trait could be for wind speed measurement which is optionally added to the thermostat.

**Comment by JudyHsiao** [comment]
Sorry for the confusion.  What i mean is the "fan speed" setting of thermostat.
Thanks for your reply.
