### ISSUE TITLE
Google Home News App Sample?

### ISSUE THREAD

**Issue by mjsevilla** [actions-on-google/actionssdk-smart-home-nodejs#53]
Are there any plans for there to be a news app sample? I can't find any documentation on how to make one.

**Comment by Fleker** [comment]
Hey @mjsevilla I'll bring up the idea with the team. It isn't really any different from any other conversational app and you can look at [other samples](https://github.com/actions-on-google) to learn more about the platform in general.

However, this doesn't relate to the Smart Home project, so I will close the issue.
