### ISSUE TITLE
Debug logs

### ISSUE THREAD

**Issue by Wade-BuildOtto** [actions-on-google/actionssdk-smart-home-nodejs#57]
How do I get them, where do I access them. I am fine to debug the program but it helps to get logs to review the results and debug errors.

**Comment by Fleker** [comment]
What kind of logs are you looking for? There's frontend logs in the Chrome developer tools, and your server-side logs are in the server instance.

**Comment by Fleker** [comment]
We have recently added [error logging with StackDriver](https://developers.google.com/actions/smarthome/logging).
