### ISSUE TITLE
No any login form

### ISSUE THREAD

**Issue by some81** [actions-on-google/actionssdk-smart-home-nodejs#59]
I don't see any username & password fields where I can login.
I can a login button only.

**Comment by Fleker** [comment]
Can you share a screenshot?

Is there something that is failing that you can identify in the Chrome Dev tools?

**Comment by some81** [comment]
<img width="1440" alt="screen shot 2017-11-08 at 11 32 11 pm" src="https://user-images.githubusercontent.com/1175133/32588523-4395da8e-c4dd-11e7-90d8-c012e8460458.png">

**Comment by some81** [comment]
<img width="1427" alt="screen shot 2017-11-08 at 11 34 20 pm" src="https://user-images.githubusercontent.com/1175133/32588541-5f98b116-c4dd-11e7-8e00-a17f785ca7e9.png">

**Comment by Fleker** [comment]
Did you follow the instructions to setup the Polymer HTML elements?

> 8. Set up the web portal

```
cd smart-home-provider/frontend
npm install -g bower
bower install
cd ..
```
