### ISSUE TITLE
QA test - "Dim the <light name>"

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/actionssdk-smart-home-nodejs#61]
Hi - 
a question, rather than issue - 
is it just me, or does that action not exist? I can set brightness percentage - but that request triggers a Query, (I can see the sense, get the current %ge) but without any specific knowledge that it then needs to trigger an EXEC, how do you handle it?

**Comment by Fleker** [comment]
To dim a light, the Home Graph first needs to know the current brightness of your lights. It first sends a `QUERY` to get that, then sends an `EXECUTE` with an absolute brightness.

**Comment by madgeni** [comment]
Thanks Fleker - just didn't see it in the documentation, it's working now :)  For reference, for others - you should return all possible trait responses inside a Query, then the API will work out what it needs. Which is both excellent, and a pain!
