### ISSUE TITLE
No Login Screen.

### ISSUE THREAD

**Issue by nakulsolanki** [actions-on-google/actionssdk-smart-home-nodejs#63]
Setup step 9 in the documentation should be updated 
from 
node smart-home-provider-cloud.js isLocal
to
node **cloud**\smart-home-provider-cloud.js isLocal

I tried running node smart-home-provider-cloud.js isLocal by changing the pwd to cloud. As a result this was rendering a blank screen.

****

this fixes the issue

**Comment by Fleker** [comment]
I have made this change in staging. I'll leave this open as a reminder for me to push the latest code changes.
