### ISSUE TITLE
fail to change device mode or toggle

### ISSUE THREAD

**Issue by JudyHsiao** [actions-on-google/actionssdk-smart-home-nodejs#64]
Hi, I am trying to  add fan with 'mode' trait, but I can not change its 'mode' or 'toggle' from the simulator. 
For example, when I input "set my living room fan fan speed to level three", the simulator always respond "Sorry, this action is not available in simulation".
when I input "set my living room fan oscillation on", the simulator still respond "Sorry, this action is not available in simulation".

But I can successfully power on/off my fan.

Here is my sync response for a fan device
```
 {  
            "type":"action.devices.types.DRYER",  // There is no devices type fan, so I use DRYER type instead...
            "traits":[  
               "action.devices.traits.OnOff",
               "action.devices.traits.Modes",
               "action.devices.traits.Toggles"
            ],
            "name":{  
               "defaultNames":[  
                  "Dyson Fan"
               ],
               "name":"fan",
               "nicknames":[  
                  "living room fan"
               ]
            },
            "willReportState":true,
            "roomHint":"living room",
            "deviceInfo":{  
               "manufacturer":"Smart Home Provider",
               "model":"g1338",
               "swVersion":"1.0.31",
               "hwVersion":"1.1"
            },
            "attributes":{  
               "availableModes":[  
                  {  
                     "name":"fan_speed",
                     "name_values":[  
                        {  
                           "name_synonym":[  
                              "speed",
                              "fan speed",
                              "level",
                              "fan speed level"
                           ],
                           "lang":"en"
                        }
                     ],
                     "settings":[  
                        {  
                           "setting_name":"one",
                           "setting_values":[  
                              {  
                                 "setting_synonym":[  
                                    "one",
                                    "1",
                                    "level one"
                                 ],
                                 "lang":"en"
                              }
                           ]
                        },
                        {  
                           "setting_name":"two",
                           "setting_values":[  
                              {  
                                 "setting_synonym":[  
                                    "two",
                                    "2",
                                    "level two"
                                 ],
                                 "lang":"en"
                              }
                           ]
                        },
                        {  
                           "setting_name":"three",
                           "setting_values":[  
                              {  
                                 "setting_synonym":[  
                                    "three",
                                    "3",
                                    "level three"
                                 ],
                                 "lang":"en"
                              }
                           ]
                        },
                        {  
                           "setting_name":"four",
                           "setting_values":[  
                              {  
                                 "setting_synonym":[  
                                    "four",
                                    "4",
                                    "level four"
                                 ],
                                 "lang":"en"
                              }
                           ]
                        }
                     ],
                     "ordered":true
                  }
               ],
               "availableToggles":[  
                  {  
                     "name":"oscillate",
                     "name_values":[  
                        {  
                           "name_synonym":[  
                              "oscillate",
                              "oscillation"
                           ],
                           "lang":"en"
                        }
                     ]
                  }
               ]
            },
            "customData":{  
               "smartHomeProviderId":"SGs84HiURHSb6ggrGjiv9jJ3t7U4ze"
            },
            "id":"4"
         }
```

**Comment by Fleker** [comment]
I'll look at this after the break. It might be the way you're giving commands is slightly incorrect.

**Comment by asturel** [comment]
Same issue here, the payload missing the 'params'

```
{ uid: '59c7a80d27e03a44449accb2',
  requestId: '2695982391929483863',
  commands:
   [ { devices: [ { id: 'klima' } ],
       execution: [ { command: 'action.devices.commands.SetToggles' } ] } ] }
```
The "execution" object should have a 'params' according to https://developers.google.com/actions/smarthome/traits/toggles#request but it just dont have it.

(I was unable to give command to control any modesetting btw..)

**Comment by Fleker** [comment]
How are you getting that object above?

**Comment by asturel** [comment]
sorry, its logged by https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/smart-home-app.js#L437

**Comment by Fleker** [comment]
So it looks like that you are getting something @asturel, in https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/smart-home-app.js#L117 you do get the execute intent. I am unsure what's going on with the payload. Can you log the entire object you receive from line 117 with `JSON.stringify` so I can check out what's happening?

@JudyHsiao can you try a statement with the same syntax that @asturel used? I want to see if the problem is related to your grammar or a problem on your server.

**Comment by asturel** [comment]
the entire reqdata (request.body): 
```
{ inputs:
   [ { intent: 'action.devices.EXECUTE',
       payload:
        { commands:
           [ { devices: [ { id: 'klima' } ],
               execution: [ { command: 'action.devices.commands.SetToggles' } ] } ] } } ],
  requestId: '5734843749710602213' }
```

**Comment by Fleker** [comment]
From [the docs](https://developers.google.com/actions/smarthome/traits/modes):

"The user can set a mode such as temperature explicitly with a command like _Set the washer’s temperature to cold._"

Does that work?

How many toggles does your device have?

**Comment by asturel** [comment]
2 toggles (here's the sync output https://pastebin.com/5rr5Efuf ), 'Set the klima's speed to low.' doesn't works, it's just a google search. :(

**Comment by Fleker** [comment]
Hey @asturel I was looking at [the docs](https://developers.google.com/actions/smarthome/traits/modes#device-attributes) and unfortunately there's currently not support for custom mode names.

"Currently, you must submit names to us so we can add support for them."

So if we don't have **speed** or a speed of **low** those commands won't work.

The same is true [for toggles](https://developers.google.com/actions/smarthome/traits/toggles#device-attributes).

**Comment by asturel** [comment]
What a bummer. So how can we know what names are supported (besides the example)?

**Comment by JudyHsiao** [comment]
Both 'turn on oscillate for living room fan.' and 'Set the living room fan's speed to three.' get this response 'Sorry, this action is not available in simulation'.

How do we  submit setting names to you so you can add support for them?

**Comment by Fleker** [comment]
Yes, settings/setting_name seems to have the same limitation.

I guess the best way is to [file a new issue](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/issues/new) on this project. I'll redirect the request internally for the time being.

**Comment by asturel** [comment]
Are we eligible to request new 'names' even if the project isn't published (and probably never will? so is it gonna be added because of 1 user?)? Will this change in the future (so we don't have to request new names)?

**Comment by rummyr** [comment]
Is there anywhere that permitted synonyms/names are listed?

**Comment by Fleker** [comment]
The doc listed above will have the ones that definitely should work. I will try to find a more comprehensive list.

**Comment by asturel** [comment]
So you didnt found a list about the available modes/toggles?

**Comment by Fleker** [comment]
We will not be publishing a full list at this time.
