### ISSUE TITLE
Published service : Device control works only 24h then relinking is required.

### ISSUE THREAD

**Issue by jenskastensson** [actions-on-google/actionssdk-smart-home-nodejs#66]
Steps to reproduce the issue:
1. select the published service and do the account linking
2. test to control devices -> works as expected, all request are received and handled by the server
3. after 24 hours, try to control a device:
-> fails with "I'm afraid there was an error and I'm unable to control your device."
->No requests are sent to the server
5. unlink the service
6. repeat step 1 - 5

This is a show stopper for us!

**Comment by Fleker** [comment]
Is this perhaps an OAuth issue? This definitely is not intentional.

Is it related to #60 perhaps? Maybe there's too many devices.

**Comment by jenskastensson** [comment]
Yes I agree it might be related to OAuth, do you have any ideas what I
should look for?

**Comment by Fleker** [comment]
Setting up your OAuth in the [OAuth playground](https://developers.google.com/actions/identity/oauth2-code-flow#validate_your_implementation) may let you identify issues.

**Comment by jenskastensson** [comment]
Thanks the OAuth playground helped!
The issue was a missing audience parameter as explained here in the Auth0
community
<https://community.auth0.com/questions/12212/accesstoken-expiration-for-action-on-google?childToView=12214#answer-12214>.
Unfortunately it is not possible to set the audience parameter from the
AoG. The only possibility on Auth0 side is to do a global setting which is
not ideal.
You can close the issue and thanks for the support!

**Comment by jenskastensson** [comment]
Additional comments on the topic  authorization url parameters:   https://community.auth0.com/comments/12264/view
------------------
Per spec if you accept an URL that represents the authorization endpoint than you should accept a query component with existing parameters and retain them when adding more. The scenario you have seems like would fall on this scenario so I don't see why Google rejects it; having said that they may not be advertising full compliance to the spec so it's their choice.

The (authorization) endpoint URI MAY include an "application/x-www-form-urlencoded" formatted query component, which MUST be retained when adding additional query parameters.
https://tools.ietf.org/html/rfc6749#section-3.1

**Comment by jenskastensson** [comment]
This issue can be closed, it was solved by using a global setting on Auth0.
It would be nice if Google supported the audience parameter as described in ietf spec.

**Comment by Fleker** [comment]
If you file a new issue outlining the feature request I'll forward the request.
