### ISSUE TITLE
Unexpected behavior when setting the temperature in German

### ISSUE THREAD

**Issue by yanniks** [actions-on-google/actionssdk-smart-home-nodejs#67]
I'm currently experimenting with the smart home Actions SDK. I recently noticed that Google Assistant does an annoying mistake when setting the temperature in German: When I say "Stell die Temperatur im Wohnzimmer auf 20 Grad" (Set the temperature in the living room to 20 degrees), it adds the temperature to the previous temperature set. I would only expect that behavior if I say "Erhöhe die Temperatur um 20 Grad" (Increase the temperature by 20 degrees).

Everything is fine if I try the same sentence in English. Even though this is not a bug in the Node.JS library, this is related to the smart home section of Google Assistant so it would be nice if you could forward that.

Thanks,
Yannik

**Comment by Fleker** [comment]
I'll forward this localization issue. Thanks.

**Comment by Fleker** [comment]
Reported issue with the localization team, so this GitHub issue will be closed.
