### ISSUE TITLE
Cannot GET / or /login

### ISSUE THREAD

**Issue by SnowPeakLiu** [actions-on-google/actionssdk-smart-home-nodejs#68]
In the Setup Instruction **Step 9**
If we follow the instruction and use `node smart-home-provider-cloud.js isLocal` command when the current path is smart-home-provider/cloud, the localhost:3000 or ngrok url is 404, since the node_module is in smart-home-provider folder. 

Instead of using  `node smart-home-provider-cloud.js isLocal` command, we should input  `node cloud/smart-home-provider-cloud.js isLocal`, then we can access the login page.

Although this is a very small issue, since I am not familiar with nodejs, it took me 2 days to find the solution.

**Comment by Fleker** [comment]
Thanks for posting this. I'm going to try to push out a few changes, including this README fix, tomorrow.

**Comment by NikolaTT** [comment]
Thank you for this! I thought I was going crazy.

**Comment by Fleker** [comment]
:+1: new changes have been made, so I'm going to close this
