### ISSUE TITLE
Question: Will blinds and shutters device type be supported?

### ISSUE THREAD

**Issue by jenskastensson** [actions-on-google/actionssdk-smart-home-nodejs#69]
Example "Open living room shutters" or "Close shutters".

As far as I can see it is not a supported device type, not OpenClose a supported trait. Do you know if it is a planned feature? 

One could argue "Open" is a potential security issue but close should be fine. 
I've noticed that "Close" works as an alternative to word to "Off" but "Open" doesn't.

**Comment by Fleker** [comment]
The way the grammars are set up, there is not a "shutters" device type, but it wouldn't necessarily be needed. If you said it was a "lightbulb", you would only need an OpenClose trait to do the action.

As you have said, it is not supported right now. We're definitely looking at a wide range of device types and enabling traits alongside partners for early-access testing.

For now, you can said "turn on living room shutters", which is a bit weird, but is a potential workaround.

**Comment by jenskastensson** [comment]
Yes it is possible to use the light device type for shutters but there's one more side effect: when "turn on the lights" will also change the shutters. Can it be avoided somehow?

**Comment by Fleker** [comment]
You could temporarily call shutters any of [the device types](https://developers.google.com/actions/smarthome/guides/). Perhaps using `action.devices.types.SCENE` would be a more suitable type.
