### ISSUE TITLE
/oauth implementation missing ?

### ISSUE THREAD

**Issue by vijmax** [actions-on-google/actionssdk-smart-home-nodejs#7]
I have named this project as bulb-test. When i goto the simulator and type "Talk to bulb test" i get a HTTP post on my server with /oauth. There is no implementation for POST method, but there is something for GET.
Is the demo implementation complete ?

**Comment by stealthflyer** [comment]
I confirmed it is working. I did notice a slight problem with the instructions so I made a pull request #8

**Comment by smishra2** [comment]
The goal of this sample is not to be a conversational app. Smart Home apps are not "invoked" in the same way as our other sample apps for Assistant. Rather, this app only supports the "actions.devices" intent, which can be used by the user if they speak commands to the Google Assistant about your devices, like "turn on my lights". Once you've followed the README and set up the sample, you should be able to test these kinds of phrases on your device, or in the web simulator.

**Comment by vijmax** [comment]
Got it ... the demo is working good now. I just had to add the https changes in smart-home-provider-cloud.js

/*HTTS changes - Start*/
var fs = require('fs');
var key = fs.readFileSync('cert/privkey1.pem');
var cert = fs.readFileSync( 'cert/cert1.pem' );
var ca = fs.readFileSync( 'cert/fullchain1.pem' );

var options = {
  key: key,
  cert: cert,
  ca: ca
};


var https = require('https');
https.createServer(options, app).listen(443);
/*Https changes - end*/

BTW ... there is one mistake in the instructions still ... 
node smart-home-provider-cloud.js smart-home-pub="https://your_domain.com"
should be changed to 
node smart-home-provider-cloud.js smart-home="https://your_domain.com"

**Comment by Fleker** [comment]
Good catch. The command is wrong.

**Comment by Fleker** [comment]
Closing this issue as you don't talk to smart home devices
