### ISSUE TITLE
Troubleshooting help: HomeGraphApiService.RequestSyncDevices

### ISSUE THREAD

**Issue by jenskastensson** [actions-on-google/actionssdk-smart-home-nodejs#70]
I'm trying to use the RequestSyncDevices but I'm having trouble, I always get "message": "Requested entity was not found.", in return. The key is a few days old. I've tried to wait a few hours after SYNC, but no success. What am I missing here?

These are my steps:
Step 1:  SYNC response include  "agentUserId"
{
  "requestId": "9277251383833896063",
  "payload": {
    "agentUserId": "ABCDEF",
    "devices": [
      {
        "id": "955-Dpart",
        "customData": {
          "syncTime": 1511873837392,

Step 2:
curl -i -s -k -X POST -H "Content-Type: application/json" -d "{agent_user_id: \"ABCDEF\"}" "https://homegraph.googleapis.com/v1/devices:requestSync?key=AIzaSyA42_6Dd-etc"

response is always 
HTTP/2 404
vary: X-Origin
vary: Referer
vary: Origin,Accept-Encoding
content-type: application/json; charset=UTF-8
date: Tue, 28 Nov 2017 14:03:54 GMT
server: ESF
cache-control: private
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
alt-svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
accept-ranges: none

{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}

**Comment by Fleker** [comment]
What if you used camelCase instead in your cURL request, as well as using single quotes for the parameters inside the body JSON for better containment, ie.

 `"{agentUserId: 'ABCDEF'}"`

**Comment by jenskastensson** [comment]
No can't the curl command to work, I'm always getting the 'not found' response. I think I've tried all combinations.
Can you run the command on your side? 
I see that in smart-home-provider-cloud.js you have an 'Authorization' parameter but it is not in the curl command, should it be in?
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + authToken
    }

**Comment by Fleker** [comment]
Have you been able to do REQUEST_SYNC when you the sample?

I removed the authorization in the latest commit because it actually did not seem to be needed.
Unless, if you add the authorization, it actually needs that parameter.

**Comment by jenskastensson** [comment]
I have only tried the command line without authorization. I have never
succeeded. It would be great to know if you can run the command line.

**Comment by Fleker** [comment]
So I tried myself in a terminal with the sample app as reference.

`curl -i -s -k -X POST -H "Content-Type: application/json" -d "{agentUserId: '1234'}" "https://homegraph.googleapis.com/v1/devices:requestSync?key=${APIKEY}"`

This gives me a 400 error. However, it also works, causing a SYNC on my server.

`agent_user_id` does the same

Could be due to not escaping your agent user id.

**Comment by jenskastensson** [comment]
That's weird, when I copy your line above 'as is' but replace ${APIKEY}
with my key (tried 4 different key) I always get a
404 Not Found
It does not cause a SYNC on my server.
The request is logged by the platform.
Some missing configuration on my side, not sure what I should look for?
[image: Inline image 1]

**Comment by jenskastensson** [comment]
PEBKAC. Thanks for the help.
