### ISSUE TITLE
Please create new Custom names for 'Modes'

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/actionssdk-smart-home-nodejs#75]
Can I have:
Control
Type
Level

Thanks

**Comment by Fleker** [comment]
`Control` and `Type` already exist. I'll look into getting level submitted.

**Comment by madgeni** [comment]
Thanks @Fleker - 
can I get some sense of what's wrong with my code then? Here's my sync for a device with mode:
`{
            "id": "470",
            "name": {
               "defaultNames": [
                  "testSelector"
               ],
               "name": "ModeSwitch"
            },
            "willReportState": true,
            "type": "action.devices.types.SWITCH",
            "traits": [
               "action.devices.traits.OnOff",
               "action.devices.traits.Modes"
            ],
            "customData": {
               "WhatAmI": "switch",
               "Who": "596699fedbbd6f42fa7891f4"
            },
            "attributes": {
               "availableModes": [
                  {
                     "name": "Control",
                     "name_values": [
                        {
                           "name_synonym": [
                              "control"
                           ],
                           "lang": "ENGLISH"
                        }
                     ],
                     "settings": [
                        {
                           "setting_name": "Off",
                           "setting_values": [
                              {
                                 "setting_synonym": [
                                    "Off"
                                 ],
                                 "lang": "ENGLISH"
                              }
                           ]
                        },
                        {
                           "setting_name": "fast",
                           "setting_values": [
                              {
                                 "setting_synonym": [
                                    "fast"
                                 ],
                                 "lang": "ENGLISH"
                              }
                           ]
                        },
                        {
                           "setting_name": "slow",
                           "setting_values": [
                              {
                                 "setting_synonym": [
                                    "slow"
                                 ],
                                 "lang": "ENGLISH"
                              }
                           ]
                        }
                     ],`
i've left the levels as fast/slow (as I understand these work) - and am using Control as the Mode. When I say 'set modeswitch control to fast' i just get an internet search. Any ideas - thanks

**Comment by Fleker** [comment]
Are you saying "modeswitch" or typing it?

The mode `Level` should be available early next week.

**Comment by madgeni** [comment]
i'm typing it actually - i've tried using 'tesSelector' in case it was getting the mode word confused. 
If i type 'set modeswitch control to off' it tells me that Mode isn't supported - but it doesn't actually query my software

**Comment by Fleker** [comment]
I'll check again whether the control grammar has been submitted. Does that work for other modes, such as a washer's "Set the washer’s temperature to cold."?

**Comment by madgeni** [comment]
I've changed the Mode to 'temperature' and the switches settings to hot/cold - same thing, i get an internet search :(
Does that sync JSON above seem right? I've not missed something that's causing this?

**Comment by Fleker** [comment]
What if you use 'load' and 'small'

"Set the <name> <mode> to <setting>"

I was able to successfully type "Set the washing machine load to small" for a washing machine with the name "washing machine". I'll continue looking into what is happening.

**Comment by madgeni** [comment]
Hi there - using load, and large/small works, but that's quite niche. 
I was wondering, rather than having you needing to hardcode settings - could the mode 'Control' be used as more of a wildcard. So if i set the Mode to Control, Google can then just pass on any settings? This would provide us with much more customisation

**Comment by Fleker** [comment]
These new modes should've been submitted by now. Please re-open if they are still not accessible.

**Comment by bueno79** [comment]
so if I have a selector "pipo" with different level/mode (small, large, huge), I can say : ok google, set pipo to huge ?

**Comment by Fleker** [comment]
@bueno79 these mode types are supported:

* xsmall
* small
* large
* xlarge

Huge is not one of them.

**Comment by bueno79** [comment]
ok but let me explain what is the need. We are using Domotic central system. It is running on multiple device/pc/pi server. This central (domoticz) control multiple device (lights, temp, pool, garage, tv,...) by wifi, zwave, 433, ...)

We need to control "Domoticz" software with Google Actions. In "Domoticz" we have some selector for different  purpose. Let me give you some examples :
- Air cooling =>Mode =off/hot/dry/cool/sync
- dry towel => mode=off/26/25/22/18
- Home cinema =>Mode=off/tv/game/NAS/BRD/DVD
- ...

so for a lot of people we don't need specific mode but a mode can be anything. So we need to say:
ok google, set [DEVICE] to [MODE]. At this moment Google need to check if it knows DEVICE, then check if this mode exists for this device.

Hope I'm clear. :) If you need my help or If you want to see the Domoticz, interface or whatever that could help you to improve Google Assistant...I'm your man. I can provide webex session, teamviewer, screenshot, skype for business session...tell me, I'm your man.

if we can control selector...I can tell you google will be THE tool of the future and competitors will have a problem ;)

cheers.

**Comment by madgeni** [comment]
I think there will be a requirement for a 'generic' mode - which when invoked passes through any setting in the JSON, without Google needing to interpret on their side.

**Comment by Fleker** [comment]
Custom modes right now are not supported, but that's definitely what you would be looking for. In the short-term I've been adding some additional hard-coded modes per user requests.

**Comment by bueno79** [comment]
Very happy to see you are moving in this direction. I'm so impatient and excited. It will be a great achievement once we will be able to use custom mode.

**Comment by madgeni** [comment]
Thanks @Fleker - appreciate you doing those requests. Are you able to progress this 'Custom' mode, which passes any setting - It's not the Mode per se, but the hard-coding of settings which is the issue here

**Comment by Fleker** [comment]
I'll be sure to let the community know about updates as they're available.

**Comment by Fleker** [comment]
@pavannandyala that's related to Assistant SDK, not smart home
