### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by reejinbouk** [actions-on-google/actionssdk-smart-home-nodejs#78]
Please tell , how it works if I have 5 homes with different ID's. For example each have 10 Lights
1. Server accept "/smarthome" POST requests and It know all devices (50 Ligths and 50 ID's). But every account (1 of 5) can control only 10 lights.
or
2. Server have for each homes some values and can identify home. Each home have 1-10 ID's of lights. 

1 or 2 is right?
thank you

**Comment by Fleker** [comment]
Good evening,
Your smart home endpoint will need to have an understanding of every device
regardless of user. The user is identified in each request through the
oauth flow, so users will have access to their own lights.

Number 1 is the correct behavior.

**Comment by reejinbouk** [comment]
Thank you!

**Comment by reejinbouk** [comment]
Number 1 

I got agentUserID at SYNC request.
Looks like this field is to identify Home.

But at which step it's generated? At authorisation? Or which?

Thank you!

**Comment by Fleker** [comment]
The `agentUserId` is a unique identifier from your OAuth server for a specific account. This may be mapped 1:1 with a Google account or may not, depending on whether multiple people have linked their Google accounts to the same account on your server.

**Comment by reejinbouk** [comment]
Explain step by step, please :)
1. User run Google Home app and choose Home for add 
2. Then it Google Home app show web page with login/password form
3. User fill login/password and press "LOGIN" button.
4. Server check login/password and send token and redirect
5. Google Home app redirected to defined page with token step 4
6. Google Home app send Sync request
7. Server response Sync

Which step is used to send agentUserId? Step 4? of 5?

Happy New Year! )

**Comment by Fleker** [comment]
1. User run Google Home app and choose your app for add
1. Then it Google Home app show web page with login/password form
1. User fill login/password and press "LOGIN" button.
1. Server check login/password and send token and redirect
1. Google Home app redirected to defined page with token step 4
1. Google Home app sends SYNC request
1. Your server should send [a SYNC response](https://developers.google.com/actions/smarthome/create-app#response)

In the `payload` of your JSON response, you should include the `agentUserId`. This is the account identifier that you have. This could be the username that the user entered to authenticate their account.

```JSON
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "payload": {
    "agentUserId": "1836.15267389",
    "devices": []
  }
}
```
