### ISSUE TITLE
Failed at the smart-home-app-sample@0.0.1 start script 'node index.js isLocal'.

### ISSUE THREAD

**Issue by citygrow** [actions-on-google/actionssdk-smart-home-nodejs#80]
Hello,

I am trying to follow the instruction to setup the Smart Home sample. However, when I tried to run the smart-home-provider-cloud.js by npm start (step 10 of instruction), the npm showed error: 

=========================================================
npm start
\> smart-home-app-sample@0.0.1 start /home/test/google/actionssdk/smart-home-provider`
\> node index.js isLocal

/home/test/google/actionssdk/smart-home-provider/cloud/smart-home-provider-cloud.js:65
  let authToken = authProvider.getAccessToken(request);
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/test/google/actionssdk/smart-home-provider/index.js:5:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-042stab111.11
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! smart-home-app-sample@0.0.1 start: `node index.js isLocal`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-home-app-sample@0.0.1 start script 'node index.js isLocal'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-home-app-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js isLocal
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-home-app-sample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-home-app-sample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/test/google/actionssdk/smart-home-provider/npm-debug.log

===========================================================

Following is the contents of the npm-debug.log:

===========================================================

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle smart-home-app-sample@0.0.1\~prestart: smart-home-app-sample@0.0.1
6 silly lifecycle smart-home-app-sample@0.0.1\~prestart: no script for prestart, continuing
7 info lifecycle smart-home-app-sample@0.0.1\~start: smart-home-app-sample@0.0.1
8 verbose lifecycle smart-home-app-sample@0.0.1\~start: unsafe-perm in lifecycle true
9 verbose lifecycle smart-home-app-sample@0.0.1\~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/test/google/actio$
10 verbose lifecycle smart-home-app-sample@0.0.1\~start: CWD: /home/test/google/actionssdk/smart-home-provider
11 silly lifecycle smart-home-app-sample@0.0.1\~start: Args: [ '-c', 'node index.js isLocal' ]
12 silly lifecycle smart-home-app-sample@0.0.1\~start: Returned: code: 1  signal: null
13 info lifecycle smart-home-app-sample@0.0.1\~start: Failed to exec start script
14 verbose stack Error: smart-home-app-sample@0.0.1 start: \`node index.js isLocal\`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid smart-home-app-sample@0.0.1
16 verbose cwd /home/test/google/actionssdk/smart-home-provider
17 error Linux 4.4.0-042stab111.11
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error smart-home-app-sample@0.0.1 start: `node index.js isLocal`
22 error Exit status 1
23 error Failed at the smart-home-app-sample@0.0.1 start script \'node index.js isLocal\'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the smart-home-app-sample package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js isLocal
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs smart-home-app-sample
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls smart-home-app-sample
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

============================================================

When after the 'npm install' in step 10, it shows warning of:

`npm WARN smart-home-app-sample@0.0.1 No repository field.`

Is there anything I am missing?

**Comment by Fleker** [comment]
What version of Node.JS and NPM are you using? Seems like you have a very old version where certain variable initializers do not work.

**Comment by citygrow** [comment]
Yes! I have just updated the node.js and npm, and now it is working! Thanks for your reply!
