### ISSUE TITLE
API solution not found with service name: homegraph.googleapis.com

### ISSUE THREAD

**Issue by citygrow** [actions-on-google/actionssdk-smart-home-nodejs#82]
I am trying to setup a new project for test, however when I want to enable the Google HomeGraph API, the Google Cloud Platform shows that: 
"API solution not found with service name: homegraph.googleapis.com"
I could find it yesterday but now I cannot, why?

**Comment by Fleker** [comment]
Do you see the API when you search for it in the Google Cloud Console?

I was able to enable it without issue.

**Comment by citygrow** [comment]
From the Google Cloud Console, I click "APIs & Services" -> "Enable APIs and services" -> and then search for "Google HomeGraph API". It shows "No results found". Following please find the screen capture.

![image](https://user-images.githubusercontent.com/32504060/34590668-3be091f6-f1f3-11e7-88ec-a96377d8c538.png)


![image](https://user-images.githubusercontent.com/32504060/34590634-0e7d69b4-f1f3-11e7-8622-ca8eb551e908.png)

I can found it before, and now I have a project running Google HomeGraph API and I want to create a new project to run another test of the Google HomeGraph API. Is it because of I already enable the Google HomeGraph API for another project, and now I cannot enable it in a new project?

**Comment by Fleker** [comment]
I believe this issue has been resolved. Can you try again?

**Comment by citygrow** [comment]
Oh! yes, I can found it now!
