### ISSUE TITLE
Brightness controls

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/actionssdk-smart-home-nodejs#83]
Hi - currently the only command for Brightness is action.devices.commands.BrightnessAbsolute - which is fine. 
However, you seem to be able to request 'dim <device name> by 25%' - which implies incremental/decremental change. However, under the hood, it makes a normal BrightnessAbsolute request, with the brightness set to 0.

Can you either remove the request command, or implement the incremental (obviously prefer the latter!)

**Comment by Fleker** [comment]
You can do a "dim by 25%".

First you implement a [`QUERY` intent](https://developers.google.com/actions/smarthome/create-app#actiondevicesquery) which will get the current brightness of your device. Then the Assistant will reduce that by the given amount and send you an absolute brightness command with the expected brightness.

Are you implementing the `QUERY` and returning the current brightness value?
