### ISSUE TITLE
Request Sync 404 error

### ISSUE THREAD

**Issue by guzmanvig** [actions-on-google/actionssdk-smart-home-nodejs#84]
When I add a lamp or anything I get a "request-sync response 404 Not Found".

I have followed every step except linking my phone to the app, since the app doesn't appear in the list of providers,  I don't know why. Anyway it should work from the simulator but it doesn't.

If I disable the homegraph api I get a 403 error, and when I enable it again I get the 404.

It's been I week since I'm trying to work around this issue without any result. 

Appreciate any help!

**Comment by Fleker** [comment]
If you haven't linked the Google Assistant to your cloud, it won't work.

Are you sure you've pressed the **TEST DRAFT** button in the Actions on Google console then see the app in your Home Control settings?

**Comment by guzmanvig** [comment]
Yes I have, I actually can use the simulator. I don't understand why it won't work if I don't link it through my phone; doesn't the simulator talk directly to the app?

**Comment by Fleker** [comment]
There is currently no UI in the simulator to handle the account linking, so your cloud should not be able to receive authorized requests until after that process

**Comment by guzmanvig** [comment]
Okey so the problem is that I am not being able to link the google assistant to my app. Do you have any idea why my app doesn't appear in the explore section of the assistant? The account I'm using in my phone is the same I used to create the project

**Comment by Fleker** [comment]
It should appear as a test app in the Home Control section of the Google Assistant settings.

**Comment by guzmanvig** [comment]
It worked! Thank you very much
