### ISSUE TITLE
Modes for AV Receiver inputs

### ISSUE THREAD

**Issue by philk** [actions-on-google/actionssdk-smart-home-nodejs#85]
Can I put in a request for some modes for setting inputs on an AV Receiver?

Mode: input / output / source
Settings: Media Player, Chromecast, Apple TV, AM/FM, Internet Radio, Satellite, Game Console, Xbox, etc etc

If they have to be generic a decent basic list would be: tuner, media player, cable, satellite, tv, usb, internet radio, bluray, aux / auxiliary, game / game console, dvd, cd

**Comment by Fleker** [comment]
Thanks for the feature request. I'll forward it.

**Comment by Fleker** [comment]
I have added the following mode:
* `input source`
* `output source`

I have added the following settings:
* `media player`
* `chromecast`
* `tv`
* `am fm`
* `internet radio`
* `satellite`
* `game console`

These changes will be live in a few days.

**Comment by philk** [comment]
Awesome, thank you!

**Comment by i8beef** [comment]
What's the correct usage here for these new mode here? I tried the following but I either don't know the magic words, or this is being silently dropped after a sync...

```
    "attributes": {
      "availableModes": [{
          "name": "input source",
          "name_values": [{
            "name_synonym": ["activity"],
            "lang": "en"
          }],
          "settings": [{
            "setting_name": "tv",
            "setting_values": [{
              "setting_synonym": ["tv", "television"],
              "lang": "en"
            }]
          }, {
            "setting_name": "meda player",
            "setting_values": [{
              "setting_synonym": ["chromecast"],
              "lang": "en"
            }]
          }],
          "ordered": false
        }]
    },
```

**Comment by peterbn** [comment]
+1 - I would also love to know how to actually use these

**Comment by i8beef** [comment]
"set (device) input source to (setting_name)"

Note that I couldn't ever get it to work by using one of the setting_synonyms.

**Comment by Fleker** [comment]
The synonyms would need to an array of valid settings. `input source` is the name and the synonym. `activity` would not be recognized by the grammar right now.

**Comment by i8beef** [comment]
Right. It also doesn't recognize the synonyms as provided for the settings, i.e., saying "set family room tv input source to chromecast" as one might expect would be possible given my above sample code does not work either, you have to set it to "media player" specifically.

I'm assuming the synonyms are just ignored right now and are there for future expansion to this sort of functionality.

**Comment by i8beef** [comment]
Really? My understanding was that you could only use the preapproved setting names listed above. If so, that's awesome and I need to make some changes.

**Comment by Fleker** [comment]
Chromecast is an existing sensor name.

**Comment by i8beef** [comment]
Ah, I was just using that as an example, I and likely a lot of others using this are really looking for custom, arbitrary mode names and setting names, and expect the synonyms to work seamlessly with whatever we choose to put in there. Still looking forward to this being expanded!
