### ISSUE TITLE
Can not load the login page

### ISSUE THREAD

**Issue by youngda** [actions-on-google/actionssdk-smart-home-nodejs#90]
Can not load the landing page, only the computer version of chrome can be loaded, my phone, Firefox, and other browsers will not work.

![image](https://user-images.githubusercontent.com/12874231/35617456-3b2f920a-06b3-11e8-96d8-f747e4cf044f.png)

![image](https://user-images.githubusercontent.com/12874231/35617493-528ab11e-06b3-11e8-8a66-e260888c69f8.png)

**I want to cry.**

**Comment by Fleker** [comment]
Yes in order to load the Polymer elements correctly, JavaScript will need to be enabled.
