### ISSUE TITLE
debug with VSCode

### ISSUE THREAD

**Issue by orcema** [actions-on-google/actionssdk-smart-home-nodejs#91]
I successfully installed the "actionssdk-smart-home-nodejs" and it works well if i launch it using the command "node index.js" within the folder "...actionssdk-smart-home-nodejs\smart-home-provider".

I need now to debug some part of the code, thus i tried to debug it using VS Code as editor and with the launch.json configured like

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

When i launch the debugger all seems to start fine, but when i use the Google Chrome browser to access the main page (http://localhost:3000/) i get as response only "Cannot GET /".

It seems like the static route defined in the file "smart-home-provider-cloud.js" 

`app.use('/', express.static('./frontend'));`

isn't matched.

So i can't figure out why launching without debugging all works fine and if a start the debugger express returns only "Cannot GET /".

I would be grateful for any help or clue for further investigation !

**Comment by Fleker** [comment]
I'm not too familiar with how VS Code does its launching. I'd have to do some investigation of it.

**Comment by orcema** [comment]
Yes in debug mode it starts and the console prints this out:
`
Debugging with inspector protocol because Node.js v8.7.0 was detected.
node --inspect-brk=46735 smart-home-provider\cloud\smart-home-provider-cloud.js 
Debugger listening on ws://127.0.0.1:46735/a7887fab-1e9a-45e9-8b34-6e545eed48ee

null: config: 
null: Object {devPortSmartHome: "3000", smartHomeProviderGoogleClientId: "[...]", smartHomeProvideGoogleClientSecret: "[...]", smartHomeProviderApiKey: "[...]", isLocal: false, …}
smart-home-app registerAgent


Registered routes:
/smart-home-api/auth
/smart-home-api/register-device
/smart-home-api/reset-devices
/smart-home-api/remove-device
/smart-home-api/exec
/smart-home-api/execute-scene
/smart-home-api/status
/smart-home-api/device-connection/:deviceId
/getauthcode
/smarthome
/smarthome
/oauth
/login
/token
Smart Home Cloud and App listening at :::3000
`

**Comment by orcema** [comment]
After long digging i found my issue. The config file for debugging was missing a config line.

> {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            **"cwd":"${workspaceRoot}/smart-home-provider"**
        }
    ]
}

**Comment by Fleker** [comment]
Glad to hear you found it!
